<a href="https://colab.research.google.com/github/amurillo98/Proyecto-Final/blob/main/Creditos_Proyecto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
creditos_proyecto = pd.read_csv("/content/drive/My Drive/Colab Notebooks/creditos_historicos.csv",sep=",")
creditos_proyecto

<ipython-input-5-4542b2df4d34>:1: DtypeWarning: Columns (13,20) have mixed types. Specify dtype option on import or set low_memory=False.
  creditos_proyecto = pd.read_csv("/content/drive/My Drive/Colab Notebooks/creditos_historicos.csv",sep=",")

,id_cliente,loan_status,loan_amnt,installment,term,emp_title,emp_length,home_ownership,annual_inc,verification_status,...,next_pymnt_d,earliest_cr_line,mths_since_last_delinq,total_pymnt,recoveries,collection_recovery_fee,last_pymnt_d,settlement_status,application_type,tot_hi_cred_lim
0,0,Current,2500,84.92,36 months,Chef,10+ years,RENT,55000.0,Not Verified,...,Mar-2019,Apr-2001,NaN,167.020000,0.0,0.0,Feb-2019,NaN,Individual,60124.0
1,1,Current,30000,777.23,60 months,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,...,Mar-2019,Jun-1987,71.0,1507.110000,0.0,0.0,Feb-2019,NaN,Individual,372872.0
2,2,Current,5000,180.69,36 months,Administrative,6 years,MORTGAGE,59280.0,Source Verified,...,Mar-2019,Apr-2011,NaN,353.890000,0.0,0.0,Feb-2019,NaN,Individual,136927.0
3,3,Current,4000,146.51,36 months,IT Supervisor,10+ years,MORTGAGE,92000.0,Source Verified,...,Mar-2019,Feb-2006,NaN,286.710000,0.0,0.0,Feb-2019,NaN,Individual,385183.0
4,4,Current,30000,731.78,60 months,Mechanic,10+ years,MORTGAGE,57250.0,Not Verified,...,Mar-2019,Dec-2000,NaN,1423.210000,0.0,0.0,Feb-2019,NaN,Individual,157548.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260663,2260663,Current,12000,279.72,60 months,house keeper,10+ years,MORTGAGE,58000.0,Not Verified,...,Mar-2019,Jan-2004,NaN,5360.960000,0.0,0.0,Feb-2019,NaN,Individual,73948.0
2260664,2260664,Fully Paid,12000,358.01,60 months,Skilled Labor,< 1 year,MORTGAGE,30000.0,Not Verified,...,NaN,Mar-2003,13.0,14499.802172,0.0,0.0,Aug-2018,NaN,Joint App,382275.0
2260665,2260665,Current,10000,332.10,36 months,Teacher,10+ years,OWN,64000.0,Source Verified,...,Mar-2019,Feb-1995,NaN,5306.940000,0.0,0.0,Feb-2019,NaN,Individual,203417.0
2260666,2260666,Current,12000,327.69,60 months,NaN,NaN,RENT,60000.0,Not Verified,...,Mar-2019,Jul-2003,7.0,5207.290000,0.0,0.0,Feb-2019,NaN,Individual,118975.0
2260667,2260667,Current,16550,451.94,60 months,BABYSITTER,3 years,RENT,60000.0,Not Verified,...,Mar-2019,Apr-2014,NaN,7355.500000,0.0,0.0,Feb-2019,NaN,Individual,50700.0

**DATA** **QUALITY**

In [ ]:
creditos_proyecto['id_cliente'].value_counts()

id_cliente
0          1
1507114    1
1507108    1
1507109    1
1507110    1
          ..
753550     1
753549     1
753548     1
753547     1
2260667    1
Name: count, Length: 2260668, dtype: int64

No existen id_cliente duplicados

In [ ]:
creditos_proyecto[creditos_proyecto.duplicated(keep=False)]

Empty DataFrame
Columns: [id_cliente, loan_status, loan_amnt, installment, term, emp_title, emp_length, home_ownership, annual_inc, verification_status, purpose, addr_state, delinq_2yrs, next_pymnt_d, earliest_cr_line, mths_since_last_delinq, total_pymnt, recoveries, collection_recovery_fee, last_pymnt_d, settlement_status, application_type, tot_hi_cred_lim]
Index: []

[0 rows x 23 columns]

No existen registros duplicados

In [ ]:
creditos_proyecto.isnull().sum()

id_cliente                       0
loan_status                      0
loan_amnt                        0
installment                      0
term                             0
emp_title                   166969
emp_length                  146907
home_ownership                   0
annual_inc                       4
verification_status              0
purpose                          0
addr_state                       0
delinq_2yrs                     29
next_pymnt_d               1303607
earliest_cr_line                29
mths_since_last_delinq     1158502
total_pymnt                      0
recoveries                       0
collection_recovery_fee          0
last_pymnt_d                  2426
settlement_status          2227612
application_type                 0
tot_hi_cred_lim              70276
dtype: int64

Definición mal pagador = loan status que tenga charged off / late (31 - 120 days) y los que tengan default y late (16-30 days) que tengan más de 3 veces vencidos en dos últimos años y que se haya vencido en el último año.